### PR TITLE
Update github links throughout docs site

### PR DESCRIPTION
**Pull request by eshaben**
### Description

This PR updates GitHub links from PureStake to the new org for each repo. Note: The XCM-SDK still lives under PureStake and so do all the Docker images.

I also added in some fixes to a few items like trailing spaces and adding a language identifies to snippets. Just some small items I was seeing across some of the pages.

CN PR: https://github.com/moonbeam-foundation/moonbeam-docs-cn/pull/307

### CODE REVIEW

**Review by themacexpert — APPROVED** [review]
Looks great! Here's my feedback:

- On learn/platform/networks/moonbase.md I found 1 old link: [Moonbase Alpha v8](https://github.com/PureStake/moonbeam/releases/tag/v0.8.0

I still some PureStake tags in the following files (not sure if they all need to be updated). Seems like the docker commands are still recognized with the PureStake tag but just flagging here just in case:
- variables.yml 
- snippets/text/full-node/macos-node.md, 
- builders/get-started/networks/moonbeam-dev.md
- tutorials/integrations/local-subsquid.md
- node-operators/networks/run-a-node/flags.md
- moonbeam-docs/node-operators/networks/run-a-node/docker.md

**Comment by eshaben** [comment]
> * On learn/platform/networks/moonbase.md I found 1 old link: [Moonbase Alpha v8](https://github.com/PureStake/moonbeam/releases/tag/v0.8.0

Good catch! Just pushed a commit 🙂 
 
> I still some PureStake tags in the following files (not sure if they all need to be updated). Seems like the docker commands are still recognized with the PureStake tag but just flagging here just in case:

Yeah, I tried with `moonbeam-foundation` instead of `purestake` and the Docker commands didn't work 🙁

**Comment by albertov19** [comment]
Interesting, can we look more into this and if there is no alternative escalate to Tim and team?

**Comment by eshaben** [comment]
I figured they were aware haha but I can talk to him yes

**Pull request merged**
