### PR TITLE
Moonbeam vs Ethereum reorg

### PR DESCRIPTION
**Pull request by eshaben**
### Description

This PR moves the Moonbeam vs Ethereum content to a new section called Core Concepts. It also cleans up the overlap in the Ethereum-related content so that the underlying technology and architecture all lives on the Technology & Architecture page and the Ethereum Compatibility page in the Features section highlights Moonbeam's Ethereum compatibility and also some key differences.

### Checklist

- [x] I have added a label to this PR 🏷️
- [x] I have run my changes through Grammarly
- [ ] If this requires translations for the `moonbeam-docs-cn` repo, I have created a ticket for the translations in Jira
- [x] If pages have been moved around, I have created an additional PR in `moonbeam-mkdocs` to update redirects

### Corresponding PRs

Please link to any corresponding PRs here.

### After Translation Requirements

- [x] Will need to create PR in `moonbeam-mkdocs` repo to add redirects for Chinese site

### CODE REVIEW

**Comment by themacexpert** [comment]
Screenshot 2024-03-18 at 11 06 46 AM
Looks like Core Concepts is missing one of these menu icons

**Review by albertov19 — DISMISSED** [review]
LGTM!

I think this could go in with a larger effort on removing some old pages on Platform?

I think we discussed this. Wdyt?

**Review by themacexpert — DISMISSED** [review]
Pushed 1 commit, looks good!

**Comment by eshaben** [comment]
> LGTM!
> 
> I think this could go in with a larger effort on removing some old pages on Platform?
> 
> I think we discussed this. Wdyt?

Yeah, I think we discussed this a while ago. But at this point, I would say separately from this PR

**Review by themacexpert — APPROVED** [review]
LGTM. I tested this with the respective branch of mkdocs corresponding to this pr and the core concepts logo looks great.

**Review by albertov19 — DISMISSED** [review]
LGTM - Are we doing redirects for such large changes?

**Comment by eshaben** [comment]
redirects added ✅  thanks!

**Comment by themacexpert** [comment]
Couple quick things I noticed the icon here is missing Screenshot 2024-04-30 at 5 48 34 PM

**Comment by themacexpert** [comment]
And Subwallet has a duplicate page 
Screenshot 2024-04-30 at 5 50 39 PM

**Review by themacexpert — APPROVED** [review]

**Comment by eshaben** [comment]
> And Subwallet has a duplicate page 

This has been like this for 5 months 🤯 😂  good catch!! The other thing is in the mkdocs PR that I linked to in my last comment

**Review by albertov19 — APPROVED** [review]
LGTM

**Pull request merged**
