### PR TITLE
Add SubQuery to Indexer Node in docs

### PR DESCRIPTION
**Pull request by seandotau**
### Description

PR to add SubQuery as an Indexer node to Moonbeam docs

### CODE REVIEW

**Comment by eshaben** [comment]
@seandotau thanks for opening the PR! 🙂  

Is this meant to be an updated version of the current SubQuery docs? https://docs.moonbeam.network/builders/integrations/indexers/subquery/

I know we haven't updated that page, it's definitely overdue.

**Comment by jamesbayly** [comment]
@seandotau you should port your changes back to the current indexer page, I thing we need to provide much documentation here on how to run a SubQuery Indexing node. We should simply link to our own docs https://academy.subquery.network/run_publish/run.html

**Comment by eshaben** [comment]
Yeah, if you want to add a page to the Node Operators > Indexer Nodes section, you're more than welcome to, but it would have to be more focused on running node infra

**Comment by eshaben** [comment]
@seandotau @jamesbayly hey! We just published some changes to the [SubQuery page](https://docs.moonbeam.network/builders/integrations/indexers/subquery/). The goal of the update was to bring it up to date and simply act as a reference on how to configure a SubQuery project for Moonbeam and how to update a project for Substrate and EVM data. If you have any feedback on it, we'd love to hear your thoughts! With that being said, I am going to go ahead and close this PR.

Aside from creating a page in the Indexer Nodes section (as I mentioned in my last comment), you could also add a page under the Tutorials section that covers a specific topic. For example, we have a tutorial that the Subsquid team submitted: https://docs.moonbeam.network/tutorials/integrations/nft-subsquid/

But there is no pressure either way! I just wanted to let you all know! Happy holidays 🥂

**Pull request closed without merging**
