### PR TITLE
Bump to client v0.36.0

### PR DESCRIPTION
**Pull request by eshaben**
### Description

This PR just updates the client version to v0.36.0!

### Checklist

- [x] I have added a label to this PR 🏷️

### CODE REVIEW

**Review by albertov19 — CHANGES_REQUESTED** [review]
Note that runtime might be 2801

**Comment by eshaben** [comment]
> Note that runtime might be 2801

This is just for the client version. If we bump to runtime 2801 and there are new docker images at that point, I'll create a new PR. Aside from that, there will be separate PRs for each network when the network upgrades to 280x

**Comment by albertov19** [comment]
Ok cool I was just thinking that some logs contain runtime 2800 word. But no biggie

**Review by albertov19 — APPROVED** [review]
LGTM

**Comment by eshaben** [comment]
> Ok cool I was just thinking that some logs contain runtime 2800 word. But no biggie

ah ok, yeah I'll make sure to update those logs once 2801 is released

**Pull request merged**
