### PR TITLE
mbip-5 available on moonbeam

### PR DESCRIPTION
**Pull request by eshaben**
### Description

As of runtime 2700, moonbeam now supports mbip-5

### Checklist

- [x] I have added a label to this PR 🏷️

### Corresponding PRs

Goes with CN PR: https://github.com/moonbeam-foundation/moonbeam-docs-cn/pull/392

### CODE REVIEW

**Review by themacexpert — DISMISSED** [review]
Looks great. There are 2 minor spelling typos here on the tx-fees page (not affected by the PR). If you have time to fix those would be great

**Review by albertov19 — APPROVED** [review]
LGTM

**Comment by eshaben** [comment]
This page needs more work, but I'll update it in a separate PR. Sorry @albertov19 - saw you just reviewed it haha, can you please review again?

**Review by albertov19 — APPROVED** [review]
LGTM

**Pull request merged**
