### PR TITLE
Update Web3js Page 

### PR DESCRIPTION
**Pull request by themacexpert**
### Description

Updates the Web3Js Page to follow new Guidelines namely View the Complete Script in page. 

### Checklist

- [ ] If this requires translations for the `moonbeam-docs-cn` repo, I have created a ticket for the translations in Jira
- [ ] If pages have been moved around, I have created an additional PR in `moonbeam-mkdocs` to update redirects
- [ ] If pages have been moved around, I have run the `move-pages.py` script to move the pages and update the image paths on the chinese repo
    - [ ] After the script has been run, I have created an additional PR in `moonbeam-docs-cn`
- [ ] If images have been added, I have run the `compress-images.py` script to compress the images.
- [ ] If variables (in variables.yml) need to be updated (such as a name change), I have updated the `moonbeam-docs-cn` repo to use the new variables
- [ ] If this page requires a disclaimer, I have added one

### Corresponding PRs

Please link to any corresponding PRs here.

### After Translation Requirements

- [ ] Will need to create PR in `moonbeam-docs` repo to remove images
- [ ] Will need to create PR in `moonbeam-docs` repo to remove variables
- [ ] Will need to create PR in `moonbeam-mkdocs` repo to add redirects for Chinese site
- [ ] No additional PRs are required after the translations are done

#### Items to be Updated

Please list any of the items that will need to be added or deleted after the translations are done here.

### CODE REVIEW

**Comment by albertov19** [comment]
@themacexpert please check this PR carefully as there are many more changes that are needed: https://github.com/moonbeam-foundation/moonbeam-docs/pull/734/files

For example:
- Change code snippets both in the snippet files and in the code snippets in the web3js.md page all `-` are `_`. For example instead of `CONTRACT-ADDRESS-....` it should be `CONTRACT_ADDRESS....`
- Add comments to the snippet files, the current ones have no comments explaining the parts.

**Comment by themacexpert** [comment]
Should be all set now

**Comment by eshaben** [comment]
@albertov19 @themacexpert as a heads up, the placeholder variables (i.e., CONTRACT_ADDRESS_HERE) should be formatted with `INSERT_VARIABLE_NAME`, so `INSERT` is always the first word followed by the variable you're describing. No need to use `_HERE` as the last word.

This is documented in the wiki and is one of the more recent changes (added right before we started Tanssi docs)

**Comment by eshaben** [comment]
I'm going to merge this into the Ethers branch since they overlap a bit

**Pull request merged**
